from base
run apt-get install -y git
run git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
run echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.profile
run echo 'eval "$(rbenv init -)"' >> ~/.profile
run git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
run rbenv install 1.9.3-p327
run rbenv rehash
